language: python
script: true
deploy:
  provider: pypi
  username: __token__
  password:
    secure: SKN+A3rJu0I8MXejdBalotvb4yfO0hmBO85T+xfGUn4Ki5GLMMi1oLZWf+EDGEvysTTCrbrhLSmGvN4QWbtilTh4gfl/MScUehR0TsVKfJsOQ7N3XEV4tFbSpJGtxN8Wm303JFP4qmNGUMKr9LfXALoGRO54PcmG/znlxxuoOSCcuZjJ7XbwUfKSYVmaauDLO67GBIX/s7Bbq63eWOjnyviSkqD4IUWeoBes9hKS8DDpNIEzmGLF77mzYWe10M65AFQyR21GuEJZZE5T6L4ZTGCvLRtXB8VEi8SGSyvIcSFFkuHyNQ3JlJ7n07/3jcbYQkmbqm6Wxe7aw2GxTtt5ZOX3Ovat8X8frD2mKzBKUdC6JVl0LORTe23HDFSQioI2Gx3iIF7FmhSZo/SPERGxv5a/H9Km3Bn3w3e+CtUydkJ5fwtk5qEC7vYatVJa0ByoZU3NrV2mOPRg6hwvfr990RPIepZ3ymByXvGdRDwE4hApl7J6cf46b60qiEb0DlVUdTN9kcMSz9bxzC7GkPn9w4ULDQjvQTB1rPuUfqTjV+0zKAVfVRWA98v7/oud66IaLnrByeCdYrldkyBBQqDCROsxRuIRc9bF7HtyNqsaTId7Eo9yJw+f+UJYbZJ8S7G6+JGKrFIPEU4Wl0q70VhOnAn7AbsBpbH/COAg5hn5T2k=
  distributions: sdist bdist_wheel
  on:
    branch: master
  skip_existing: true
